package org.midstr.designPattern.factory.abstractfactory;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AbstractProduct.java
//  @ Date : 2010-1-4
//  @ Author : 
//
//




public abstract class AbstractProduct {
}
