package org.midstr.designPattern.factory.abstractfactory;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 2010-1-4
//  @ Author : 
//
//




public class Client {
}
