package org.midstr.designPattern.factory.factorymethod;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Creator.java
//  @ Date : 2010-1-4
//  @ Author : 
//
//




public abstract class Creator {
	public void FactoryMethod() {
	
	}
}
